name: Khristopher Carlson
favicon: null
layout_spectrum: 0.5285
typography_spectrum: 0.63747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020204'
    - '#7DA1AD'
    - '#F6F2E6'
    - '#5D666F'
    - '#E6AF77'
  brandStrength: 0.25
  lightness: 0.875
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
