layout_spectrum: 0.6630824
color:
  saturation: 0.2706093
  lightness: 0.9128332
  brandStrength: 0.1308244
  brandColors:
    - '#020204'
    - '#7DA1AD'
    - '#F6F2E6'
    - '#5D666F'
    - '#E6AF77'
  rhythmicContrast: 0.07531207
typography_spectrum: 0.9032258
name: Khristopher Carlson
